#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-influxdb-java
Version  : 2.14
Release  : 1
URL      : https://github.com/influxdata/influxdb-java/archive/influxdb-java-2.14.tar.gz
Source0  : https://github.com/influxdata/influxdb-java/archive/influxdb-java-2.14.tar.gz
Source1  : https://repo1.maven.org/maven2/org/influxdb/influxdb-java/2.14/influxdb-java-2.14.jar
Source2  : https://repo1.maven.org/maven2/org/influxdb/influxdb-java/2.14/influxdb-java-2.14.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: mvn-influxdb-java-data = %{version}-%{release}
Requires: mvn-influxdb-java-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
# influxdb-java
[![Build Status](https://travis-ci.org/influxdata/influxdb-java.svg?branch=master)](https://travis-ci.org/influxdata/influxdb-java)
[![codecov.io](http://codecov.io/github/influxdata/influxdb-java/coverage.svg?branch=master)](http://codecov.io/github/influxdata/influxdb-java?branch=master)
[![Issue Count](https://codeclimate.com/github/influxdata/influxdb-java/badges/issue_count.svg)](https://codeclimate.com/github/influxdata/influxdb-java)

%package data
Summary: data components for the mvn-influxdb-java package.
Group: Data

%description data
data components for the mvn-influxdb-java package.


%package license
Summary: license components for the mvn-influxdb-java package.
Group: Default

%description license
license components for the mvn-influxdb-java package.


%prep
%setup -q -n influxdb-java-influxdb-java-2.14

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-influxdb-java
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-influxdb-java/LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/influxdb/influxdb-java/2.14
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/influxdb/influxdb-java/2.14/influxdb-java-2.14.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/influxdb/influxdb-java/2.14
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/influxdb/influxdb-java/2.14/influxdb-java-2.14.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/influxdb/influxdb-java/2.14/influxdb-java-2.14.jar
/usr/share/java/.m2/repository/org/influxdb/influxdb-java/2.14/influxdb-java-2.14.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-influxdb-java/LICENSE
